In [1]:
A = [1,2,3,4,5]
B =[3,4,5,6,7] 

sort_list = list(set(A) - set(B[0:2]))
print(sort_list)

[1, 2, 5]


In [2]:
import numpy as np

A = [1,2,3,4,5]
B =[3,4,5,6,7]
c = np.outer(A,B).transpose()

print(c)

[[ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]
 [ 7 14 21 28 35]]
